/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iflytek_mscv5plusdemo_jni_JNIActivity */

#ifndef _Included_com_iflytek_mscv5plusdemo_jni_JNIActivity
#define _Included_com_iflytek_mscv5plusdemo_jni_JNIActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_iflytek_mscv5plusdemo_jni_JNIActivity
 * Method:    getStrFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_iflytek_mscv5plusdemo_jni_JNIActivity_getStrFromJni
  (JNIEnv *, jobject);

/*
 * Class:     com_iflytek_mscv5plusdemo_jni_JNIActivity
 * Method:    getIntpro
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_iflytek_mscv5plusdemo_jni_JNIActivity_getIntpro
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
